Slider Responsiveness
kingsmen732/Zapfolio pull request #72
Opened 2024-10-14 17:48 UTC by smt96700

Adjusted the responsive behavior of the slider component to improve usability on mobile devices.

2024-10-14 18:00 UTC, kingsmen732 commented
Can you please use the latest version from the repo and include your feature request  @smt96700

2024-10-14 19:21 UTC, smt96700 commented
I have updated my feature request and ensured compatibility with the latest version of the repository; please review the changes and feel free to suggest any improvements.

2024-10-15 08:39 UTC, kingsmen732 requested changes
Kindly look into the project section close buttons. Your feature request is not responding as it is tampered with in your base. Rest assured, other features are working pretty cool.

2024-10-15 10:07 UTC, smt96700 commented on src/components/modals/ProjectModal.jsx
> +          onClick={() => props?.onClose()}
I have replaced incorrect setIsModalOpen  with onClose  function to resolve modal close functionality.

2024-10-15 11:40 UTC, kingsmen732 commented on src/components/modals/ProjectModal.jsx
> +          onClick={() => props?.onClose()}
Thanks, There is some issue of touch sensitivity in mobile view that they cannot scroll down and if they try the page changes.

2024-10-16 03:41 UTC, smt96700 commented on src/components/modals/ProjectModal.jsx
> +          onClick={() => props?.onClose()}
Got it will review it soon.

2024-10-20 05:42 UTC, smt96700 commented on src/components/modals/ProjectModal.jsx
> +          onClick={() => props?.onClose()}
I've refined the slider's responsiveness for an enhanced mobile experience. Please review the changes.

2024-10-22 09:49 UTC, smt96700 commented
Could you please review the pr I have updated my local branch with the current version of the main branch.

2024-10-30 08:33 UTC, merged